import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

describe('V7 本地组合入口', () => {
  it('提供当前 V7 桌面启动/停止入口和公开入口说明', () => {
    const root = process.cwd();
    const start = readFileSync(resolve(root, '文秘写作-启动.cmd'), 'utf8');
    const stop = readFileSync(resolve(root, '文秘写作-停止.cmd'), 'utf8');
    const launcher = readFileSync(resolve(root, 'scripts/start-desktop.ps1'), 'utf8');
    const shortcutCreator = readFileSync(resolve(root, 'scripts/create-desktop-shortcut.ps1'), 'utf8');
    const processLauncher = readFileSync(resolve(root, 'scripts/start.mjs'), 'utf8');
    const stopper = readFileSync(resolve(root, 'scripts/stop-desktop.ps1'), 'utf8');
    const readme = readFileSync(resolve(root, 'README.md'), 'utf8');
    expect(start).toContain('start-desktop.ps1');
    expect(start).toContain('set "WENMI_SAVED_PATH=%PATH%"');
    expect(start).toContain('set "Path="');
    expect(start).toContain('set "PATH=%WENMI_SAVED_PATH%"');
    expect(stop).toContain('stop-desktop.ps1');
    expect(launcher).toContain("Start-Process 'http://127.0.0.1:43110'");
    expect(launcher).toContain('Resolve-WenmiNodePath');
    expect(launcher).toContain('node-v24.16.0-win-x64');
    expect(launcher).toContain("Join-Path $nodeDirectory 'npm.cmd'");
    expect(launcher).toContain("$candidateNpm = Join-Path (Split-Path -Parent $candidate) 'npm.cmd'");
    expect(launcher).toContain('& $npmPath run migrate');
    expect(launcher).toContain('& $npmPath run build');
    expect(launcher).toContain('$health.data.releaseId -eq $expectedReleaseId');
    expect(launcher).toContain('*<div id="root"></div>*');
    expect(launcher).toContain('Test-WenmiReady');
    expect(launcher).toContain('Test-WenmiBuildStale');
    expect(launcher).toContain("& (Join-Path $PSScriptRoot 'stop-desktop.ps1')");
    expect(processLauncher).toContain('startedAtUtc');
    expect(launcher).toContain("[Environment]::SetEnvironmentVariable($name, $value, 'Process')");
    expect(launcher).toContain('Start-Process -FilePath $nodePath');
    expect(launcher).toContain('-WindowStyle Hidden');
    expect(launcher).toContain('-RedirectStandardOutput $stdoutPath');
    expect(launcher).toContain('-RedirectStandardError $stderrPath');
    expect(launcher).not.toContain("& cmd.exe /d /c start 'Wenmi Writing' /b");
    expect(launcher).not.toMatch(/[^\x00-\x7f]/u);
    expect(processLauncher).toContain("execFileSync('reg.exe'");
    expect(processLauncher).toContain("'HKCU\\\\Environment'");
    expect(processLauncher).not.toContain('console.log(value)');
    expect(processLauncher).toContain('delete nonModelEnvironment[name]');
    expect(processLauncher).toContain("spawnService('API', process.execPath, ['apps/api/dist/main.js'], apiEnvironment)");
    expect(stopper).toContain("scripts/start.mjs");
    expect(stopper).toContain('Refusing to stop');
    expect(stopper).toContain('desktop-stop.request.json');
    expect(stopper).not.toContain('Get-CimInstance');
    expect(processLauncher).toContain('consumeVerifiedStopRequest');
    expect(shortcutCreator).toContain("[Environment]::GetFolderPath('Desktop')");
    expect(shortcutCreator).toContain('CreateShortcut($shortcutPath)');
    expect(shortcutCreator).toContain('$productName = -join');
    expect(shortcutCreator).toContain("$shortcutPath = Join-Path $desktop ($productName + '.lnk')");
    expect(shortcutCreator).toContain('$shortcut.WorkingDirectory = $projectRoot');
    expect(readme).toContain('V7 是当前唯一产品版本');
    expect(readme).toContain('https://wenmixiezuo.com/');
    expect(readme).toContain('http://127.0.0.1:43110/');
    expect(readme).not.toContain('docs/USER_GUIDE.md');
  });
});
