// Keep public types and error classes identical across both storage adapters.
export { OPENING_DECISION_FIELDS, OpeningAgentModelError, OpeningAgentStoppedError } from '@wenmi/opening-runtime';
export type {
OpeningAgentTaskKind,
OpeningAgentWorkstationKey,
OpeningAgentOperationMode,
OpeningCandidateKind,
OpeningPublishingPlatform,
OpeningTaskStatus,
OpeningTaskPhase,
OpeningWorkOrder,
OpeningProtagonist,
OpeningPackage,
OpeningTaxonomyReference,
OpeningReviewIssue,
OpeningDecisionField,
OpeningReviewDecision,
OpeningReview,
OpeningCandidateContent,
OpeningSavedCandidate,
OpeningModelAttempt,
OpeningAgentTaskState,
OpeningIdeaSnapshot,
OpeningInternalReference,
OpeningReferencePack,
OpeningModelRequest,
OpeningReconciliationRequest,
OpeningModelResult,
OpeningReconciliation,
OpeningAgentModelGateway,
OpeningCandidateCommit,
OpeningAgentToolGateway,
OpeningStructuredGeneration,
OpeningNodeSpecification
} from '@wenmi/opening-runtime';
