// R187逐项编辑：条件描述具体创作需求，不从旧适用范围或类别推导。
// 五列顺序：全书方向、粗分卷、卷、链、章；o=按需，-=不自动提供。
export const AUDITED_PATTERN_RULES = `
mission-chain|--oo-|长期目标可拆成前后有联系的任务；避免重复接单只换敌人。
dungeon-expedition|--oo-|故事需要进入边界明确的探索区；先明确进入目的和离开条件。
tournament-bracket|--oo-|名次和晋级确实影响人物目标；不同轮次应有不同问题。
qualification-trial|--ooo|人物需要取得资格或证明能力；不把所有成长都改成考试。
academy-assessment|--oo-|学院生活和考核影响当前人物选择；不要只堆排名。
workplace-project|--oo-|职业故事围绕交付成果展开；明确职责、资源和验收方。
commercial-bidding-war|--ooo|几方争同一合同且各有方案；不能只靠报价高低替代竞争。
public-performance|--ooo|作品或能力需要公开呈现；反应来自演出效果及观众立场。
sports-match|--ooo|当前比赛有明确规则和胜负目标；一章只承担本场的相应部分。
military-campaign|--oo-|故事涉及连续军事行动；区分战略目的与单次交锋。
siege-defense|--oo-|据点内外相互制约形成主冲突；不能忽略出入、补给和内部选择。
infiltration-operation|--ooo|身份暴露会妨碍目标；潜入、取证和撤离可分开设计。
undercover-assignment|--oo-|伪装身份持续影响关系与行动；不同于一次换装混入。
heist-operation|--ooo|夺取受保护目标需要策划配合；章节只展开当前行动。
escort-mission|--oo-|人或物必须安全抵达；路线与被护送者应影响行动。
rescue-operation|--ooo|有人受困且需要外力帮助；以具体受困条件决定办法。
pursuit-escape|--ooo|追踪不断影响逃亡路线；不能用无限追兵维持重复紧张。
survival-shelter|--oo-|稳定据点是人物生存目标；同时考虑物资与共同生活。
disaster-response|--ooo|灾害改变当前行动条件；人物的专业能力和选择要有作用。
investigation-case|--oo-|当前单元要回答具体未知；明确已知事实和待验证判断。
closed-circle-case|--oo-|人员范围或出入条件受限；封闭不代表必然存在内部凶手。
treasure-hunt|--oo-|目标值得寻找且线索推动路线；不靠连续巧合送到手。
frontier-expedition|--oo-|探索未知本身有目的与回报；未知环境需要逐步建立可理解特点。
lost-realm-exploration|--oo-|遗迹历史会影响当前探索；不用强制每处遗迹都藏灭世灾难。
road-journey|--oo-|移动中的遭遇构成故事；路线变化与人物关系应互相影响。
migration-exodus|--oo-|群体迁移带来资源、去留或秩序问题；区分个人旅行。
rebellion-uprising|--oo-|组织反抗构成当前主线；兼顾不同参与者目的，不预定善恶结论。
succession-contest|--oo-|共同权位确有多个竞争者；依据本世界继承规则安排冲突。
court-debate|--ooo|公开议决会改变利益分配；发言必须对应人物诉求与权限。
institutional-purge|--oo-|排除内部威胁构成事件；保留证据真假和误伤的可能。
negotiation-summit|--ooo|双方各有筹码且存在交换空间；明确谈不成的后果。
trial-courtroom|--ooo|争议进入正式裁决；依据世界既有程序，不照搬现实法律。
reform-pilot|--oo-|新制度需要通过局部实践检验；反对方也应有具体利益。
territory-development|--oo-|建设与管理是当前追读动力；不把土地扩大等同治理成功。
settlement-building|--oo-|临时群体开始共同生活；需要基础设施与分工逐步成立。
production-crisis|--ooo|生产瓶颈会影响目标；明确是哪一环出问题及替代选择。
auction-trade-fair|--ooo|交易场合同时推动资源或关系变化；拍卖不是必套冲突。
banquet-social-game|--ooo|人物受公开礼仪或身份约束；隐藏冲突通过行为体现。
wedding-ceremony|--ooo|关系承诺受到家庭或社会见证；不强制加入抢婚和破坏。
family-gathering|--ooo|共同场合让家庭分歧浮现；也可承担温暖日常。
reunion-return|--ooo|旧人旧地与现在形成对照；需要让变化影响当前感受或决定。
relationship-crossroads|--ooo|双方对未来存在明确分歧；允许选择继续、调整或结束。
caregiving-period|--oo-|持续照护确实改变相处；被照护者也保留行动和选择。
mentorship-apprenticeship|--oo-|能力学习与师承关系共同推进；不能只有师父讲解。
team-formation|--ooo|任务需要不同成员共同承担；组队过程体现各自诉求。
recruitment-selection|--ooo|成员与组织需要相互选择；名额与标准应符合当前处境。
ritual-festival|--ooo|公共仪式能呈现关系或世界生活；无需每次发生事故。
time-loop-scenario|--oo-|重复时间是当前核心机制；明确保留什么记忆与改变。
conceal-capability|--ooo|暂不暴露能力有具体收益或趣味；不强迫无敌主角永远装弱。
disguise-identity|--ooo|身份差异可以改变进入资格或他人反应；说明伪装用途。
embed-and-observe|--ooo|行动前确需了解内部关系；观察应获得能用的信息。
bait-and-catch|--ooo|隐藏对手可能主动回应诱因；诱饵要符合对方需求。
feint-and-shift|--ooo|对手资源会被假目标吸引；真实目标与转移过程需清楚。
divide-coalition|--ooo|对方联盟确有利益分歧；不能一句挑拨就让所有人失智。
borrow-power|--ooo|现有力量或制度能被利用；明确借势条件与实际作用。
information-arbitrage|--ooo|信息差能改变决策收益；避免把作者未交代的信息当主角全知。
negotiated-exchange|--ooo|双方各有对方需要的筹码；交换结果可以有限而非皆大欢喜。
exploit-rules|--ooo|既定规则留有可用空间；大胆解法也要说清利用了什么。
build-alliance|--ooo|合作能满足最低共同利益；允许保留内部矛盾。
turn-opponent|--ooo|对手存在可改变立场的理由；改变可以只是暂时停战。
sacrifice-short-term|--ooo|眼前与长期收益冲突；让放弃服务目标，不强制吃亏。
strategic-retreat|--ooo|继续投入不利且存在退出机会；撤退应留下下一步空间。
proxy-contest|--ooo|直接对抗受限或需隐蔽；代理人仍有自己的利益。
parallel-plans|--ooo|结果不确定且有条件准备备选；避免事后声称早就算到一切。
countertrap|--ooo|人物已获得足够识破线索；反制针对陷阱的具体弱点。
public-demonstration|--ooo|旁观者判断影响目标；用看得见的结果改变认识。
evidence-sting|--ooo|需要让隐藏行为留下记录；诱捕条件不能凭空出现。
controlled-disclosure|--ooo|公开时机与对象会影响局势；区别角色策略和作者故意藏信息。
empathy-repair|--ooo|人物愿意承担已造成伤害；补偿不等于要求对方原谅。
learn-by-apprenticeship|--ooo|人物缺乏某项能力并选择学习；允许压缩重复练习。
team-specialization|--ooo|复杂行动可按专长分工；保留协作失败或临场调整空间。
innovation-breakthrough|--ooo|新组合能解决旧办法的问题；创意尺度服从作者选择。
deadline-pressure|--ooo|存在真实截止条件；时间减少需要影响可选办法。
resource-scarcity|--ooo|稀缺确实影响行动；不能给作者设定的无限能力偷偷加限制。
overwhelming-opponent|--ooo|实力差距能产生预期体验；不要求每个故事先被强敌羞辱。
public-scrutiny|--ooo|旁观或记录改变人物行为；不必所有围观者立场一致。
reputation-risk|--ooo|信用对人物目标有实际价值；避免只写抽象丢脸。
hierarchy-pressure|--ooo|上位者确有资源或惩罚权；压制方式服从世界规则。
institutional-constraint|--ooo|规则限制最直接办法；可以突破或改变，不能假定永远服从。
hostage-bind|--ooo|被控制对象确实为人物所重视；不要用反复绑架代替人物塑造。
collateral-risk|--ooo|行动会影响目标外的人或事；是否取舍由人物与作者方向决定。
injury-illness|--ooo|已有身体或心理状态影响行动；不把伤病当固定性格。
hostile-environment|--ooo|环境能实际改变路线或消耗；不要只作形容词背景。
isolation-pressure|--ooo|援助与联系被切断；仍可通过有限资源主动解决。
persistent-pursuit|--ooo|追捕持续改变行动条件；需要说明追踪如何延续。
betrayal-suspicion|--ooo|有异常而证据不足；区分怀疑与已经确认的背叛。
internal-faction-split|--ooo|同阵营对目标或办法有分歧；保留各方立场的具体依据。
moral-dilemma|--ooo|两种重要价值确实不能兼得；不用人为删掉可行解法造虐。
secret-exposure|--ooo|秘密公开会改变资格、安全或关系；明确谁知道什么。
debt-obligation|--ooo|旧承诺已经成立且到了兑现时机；不能凭空加债。
responsibility-expansion|--ooo|新位置带来实际责任；是否承担可以成为人物选择。
conflicting-objectives|--ooo|两个目标在时机或手段上冲突；不要把普通忙碌写成必然两难。
unreliable-intelligence|--ooo|决策资料缺失或不可靠；标明人物知道的与作者知道的区别。
rule-trap|--ooo|多项规则组合造成困境；读者应能理解陷阱如何成立。
repeated-failure|--ooo|重复受挫能暴露旧办法的问题；无效重复应压缩或删去。
irreversible-loss|--ooo|作者接受永久失去且它对后续有作用；不能作为每个阶段的必需项。
false-victory|--ooo|眼前成功与长期意义不同；仍应承认已取得的真实成果。
false-defeat|--ooo|表面失败产生可用条件；不可用解释抹去实际损失。
identity-reveal|--ooo|隐藏身份对当前关系有影响；揭露依据服从所选叙事风格。
ally-betrayal|--ooo|盟友有改变立场的动因；不为制造反转随意改性格。
enemy-cooperation|--ooo|共同威胁或利益超过眼前敌意；合作不等于永久和解。
goal-redefinition|--ooo|新信息使原目标不再合适；改目标需保留此前经历的意义。
hidden-cost-reveal|--ooo|已有机制或交易还有未知成本；不能借此随意否定作者金手指。
evidence-reframed|--ooo|新语境改变旧证据含义；原事实不应被偷偷改写。
rule-reinterpreted|--ooo|原规则有未理解的边界；区别发现解释与修改规则本身。
status-reversal|--ooo|胜负或制度变化足以改变位置；表现新权力带来的行动差异。
location-becomes-trap|--ooo|目的地被误判为安全；陷阱来源应能解释。
loop-clue-breakthrough|--ooo|时间循环已成立且差异可追踪；变化须对下一次行动有用。
presumed-dead-return|--ooo|人物此前只是被认为死亡或失踪；已确认死亡须遵守复活设定。
legacy-inheritance-reveal|--ooo|遗产关联未明历史或责任；可带来惊喜，不强制附赠诅咒。
culprit-reversal|--ooo|调查证据改变责任判断；公平推理不得临时引入未铺垫真凶。
third-force-intervention|--ooo|第三方有参与动机与条件；不把救场当成自动解决一切。
success-triggers-crisis|--ooo|成功触发可解释的新反应；不要求每次获胜立刻受罚。
sacrifice-shifts-balance|--ooo|人物主动付出能改变局势；不默认只有死亡才算牺牲。
misunderstanding-clarified|--ooo|误会解决后确实还有真实分歧；没有剩余冲突时允许和解。
plan-within-plan-exposed|--ooo|公开行动确实服务另一目标；保留前面可理解的线索。
public-vindication|--ooo|外界曾有具体误判；认可可因立场不同而分化。
capability-breakthrough|--ooo|新能力落实成长或金手指承诺；获得方式服从本书设定。
rank-promotion|--ooo|职位等级会改变行动权限；不把一切成长等同晋升。
resource-acquisition|--ooo|资源是已建立目标的回报；明确实际用途。
rescue-completed|--ooo|主要危险已经解除；获救者后续选择可继续展开。
escape-secured|--ooo|当前追捕或封锁已被切断；不要只换地点就宣称安全。
truth-revealed|--ooo|当前谜团到达回答时机；只兑现本层负责的问题。
justice-enforced|--ooo|追责是作品需要的回报；结果依本世界制度与人物选择。
revenge-stage-settled|--ooo|当前责任人或旧债得到处理；不必每次复仇都暴露更大幕后。
relationship-confirmed|--ooo|双方已作出相应选择；不能由旁白替双方承诺。
trust-repaired|--ooo|受损信任已有修复依据；允许只恢复有限合作。
family-reconciled|--ooo|家庭线需要阶段结果；和解、设立边界或保持距离都可成立。
team-cohesion|--ooo|共同经历足以形成合作基础；不要求成员从此没有分歧。
territory-gained|--ooo|取得新空间或市场服务经营目标；是否治理和如何治理另行展开。
institution-changed|--ooo|争取的规则变化开始生效；执行阻力可留给后续。
championship-result|--ooo|比赛到了结算节点；冠军、失利或突破都可兑现本段目标。
commercial-win|--ooo|经营成果可以被验证；销售、利润、用户认可不要混成同一指标。
artistic-recognition|--ooo|作品完成并得到反馈；评价应体现不同受众。
survival-secured|--ooo|最迫切风险已被控制；阶段稳定不代表永远安全。
secret-protected|--ooo|当前传播风险得到控制；是否付代价依具体剧情。
moral-victory|--ooo|守住价值比外部胜负更重要；不能替作者把爽感回报换成说教。
tragic-sacrifice|--ooo|作者接受悲剧且牺牲兑现人物目标；不要机械拿配角死亡催泪。
bittersweet-exchange|--ooo|当前事件同时带来收获与遗憾；不预定全书结局或永久失去。
new-world-opened|--ooo|阶段结果提供新舞台入口；新舞台要承接旧经历。
recovery-period|--ooo|已有损耗需要处理；恢复可压缩，不强制单列水章。
daily-life-window|--ooo|生活细节提供陪伴、趣味或人物关系；不必附带危机。
training-consolidation|--ooo|人物要稳定刚获得的能力；依据缺口安排练习。
travel-transition|--ooo|地点确实改变；展开旅途仅在有体验或事件价值时。
investigation-followup|--ooo|已有线索需要重排；复盘应导向判断或行动。
resource-settlement|--ooo|收获分配影响后续行动或关系；无作用的细账可省略。
relationship-aftercare|--ooo|大事件影响关系；回应可以温暖、回避、冲突或重新约定。
mourning-ritual|--ooo|人物需要回应真实失去；不同角色可以有不同表达。
celebration-window|--ooo|成功值得停留和享受；不强制庆祝时马上出事。
political-aftermath|--oo-|胜负改变权力与联盟；聚焦与后续故事有关的反应。
career-market-aftermath|--oo-|成果影响职业与市场；不要只有抽象全网震惊。
world-reaction|--ooo|主角行为确实影响外部群体；按传播范围展示差异。
foreshadow-seed|--ooo|后续有明确可用的触发点；没有回收打算不必堆伏笔。
next-mission-intake|--ooo|旧任务已有结算，新问题值得承担；允许主角主动选择。
time-skip-transition|--ooo|稳定重复期可跳过；保留影响后续的人物和资源变化。
perspective-handoff|--ooo|另一人物承接了当前结果；视角切换须符合已选叙述方式。
grow-into-responsibility|--oo-|责任成长是本段动力；人物不必先被写成无能或自私。
loss-and-rebuild|--oo-|作者需要失去依靠后重建的过程；不擅自摧毁已有全部成果。
escalating-consequences|--oo-|解决旧事自然扩大目标；也允许出现稳定阶段。
layered-truth|--oo-|多个层次的疑问共同构成调查过程；分配每层回答责任。
balance-of-power|--oo-|多方各有筹码与底线；换边应来自利益或认知变化。
relationship-redefines-goal|--oo-|关系变化会实际改变行动目标；不强行加恋爱线。
accumulate-and-stress-test|--oo-|建立的体系需要接受检验；检验不必导致崩塌。
trigger-and-response|--ooo|具体问题打破原处境；人物回应要符合当时能力与目标。
capability-under-pressure|--ooo|误判或限制影响目标；用行动结果改变判断，不强制先羞辱。
victory-with-cost|--ooo|阶段胜利确有新成本；不能让所有成功都失去回报。
failure-to-breakthrough|--ooo|旧办法受挫能带来新认识；可以小失误，不必重伤或死人。
clues-reframe-understanding|--ooo|一个有边界的小问题需要证据重释；新理解必须影响行动。
factions-change-sides|--ooo|阵营变化是当前事件转向；角色立场要有依据。
relationship-forces-choice|--ooo|共同行动使关系必须表态；允许不同选择，不预定相爱或和解。
hope-loss-choice|--ooo|作者选择先扬后抑的体验；后果应服务最后选择。
dungeon-expedition-run|--oo-|要设计完整探索、应变与离开过程；不强制永久损失。
tournament-run|--oo-|多轮竞争形成完整单元；各轮承担不同作用。
academy-growth-cycle|--oo-|学习、关系与考核共同构成阶段；避免同一种考试重复。
staged-revenge|--oo-|复仇涉及多层责任或因果；不凭空加幕后拖延兑现。
fair-case-investigation|--oo-|作者需要可回看验证的推理案件；先安排真相与证据责任。
infiltration-and-extraction|--oo-|潜入和安全撤出共同构成目标；允许成功不暴露。
countdown-rescue|--oo-|救援存在明确期限；阻碍来自具体条件，不重复制造意外。
survival-collapse-rebuild|--oo-|既有生存体系失效是当前起点；不能擅自推翻作者已确认稳定状态。
campaign-to-aftermath|--oo-|战役胜负与其后果共同重要；卷链按规模分配，章只承接片段。
court-power-struggle|--oo-|权力结果来自公开规则与私下行动；不要把所有人写成全知棋手。
kingdom-building-cycle|--oo-|建设成果需要经受内外检验；不强制领地每卷重建。
business-war-cycle|--oo-|产品与竞争形成经营阶段；真实经营指标依本书世界设定。
workplace-project-cycle|--oo-|项目能改变职业处境；失败不是固定必经步骤。
entertainment-rise-cycle|--oo-|创作到公开反馈构成完整过程；争议和成名不必同时发生。
sports-championship-cycle|--oo-|赛季或系列比赛需要长期铺排；允许不同形式的终局成绩。
romance-commitment-cycle|--oo-|亲密关系是当前核心线；承诺由双方选择，不靠误会硬拖。
marriage-crisis-repair|--oo-|已有婚姻面临具体问题；修复、重订或结束都允许。
family-legacy-cycle|--oo-|旧事影响当下家庭责任；不强制安排隐藏血缘或巨额遗产。
science-discovery-cycle|--oo-|发现、验证与应用选择构成故事；并非每次发现都必须有伦理灾难。
apocalypse-refuge-cycle|--oo-|末世群体建设避难所；内部制度和外部威胁按故事取舍。
infinite-instance-cycle|--oo-|规则区进入与脱离是完整单元；解法可突破而不必钻漏洞。
`.trim();
