// R187人工逐项判断，旧applicableScopes不参与归类计算。
export const AUDITED_NARRATIVE_RULES = `
single-core-line|cio--|全书围绕一个持续目标展开，其他线服务它。
dual-lead-braid|oio--|两位主角都有独立目标，并影响彼此命运。
multi-line-network|cio--|至少两条主线确实需要独立推进与交汇。
multi-line-convergence|oioo-|已建立的多条线要在关键阶段汇合。
episodic-spine|cio--|依靠多个相对独立故事持续推动长期主线。
ensemble-network|oio--|核心卖点是多个人物共同改变局势。
frame-story|oioo-|讲述、调查或记录本身也是一层故事。
parallel-contrast-structure|oio--|两条长期故事线需要对照，而不是最终汇合。
linked-anthology|oio--|作者明确选择共享主题或世界的独立故事集。
nested-thread-weave|ooo--|多线已确立，当前需要安排开线、回访和收线。
mosaic-network|oio--|作品依靠不同人物或材料拼出整体图景。
story-completeness|rrrrr|复核当前是否交代局面、变化和阶段结果，不强制每章完整闭环。
three-act|cicoo|需要组织一个目标、对抗与解决构成的完整故事。
four-act|cicco|需要组织处境、发展、关键转向和阶段收束。
five-act|cicoo|故事需要压力上升、高点、后果与收束的阶段变化。
six-act|cicco|需要区分进入、转向、升级、危机、重整、解决；不绑定卷数。
hero-journey|oiooo|人物进入陌生世界，经考验后改变能力或认知。
eight-sequence|oioo-|当前故事较长，需要区段分工，不能按八等份机械切分。
seven-point|oiooo|需要围绕核心问题安排转向、施压和主动突破。
story-circle|cicco|需要梳理人物需要、取得、付出和改变。
save-the-cat|oioo-|需要以卖点、转向与危机组织商业故事，不固定比例。
truby-22|--oo-|已经进入具体人物与冲突设计，需要较细的欲望、弱点和对手规划。
field-paradigm|oioo-|需要突出进入任务和改变行动方向的两个关键转折。
fichtean-curve|oiooo|故事以连续危机推进，符合作者选定的阅读体验。
kishotenketsu|oiooo|日常、探索或反差故事主要靠视角变化，而非敌我对抗。
story-spine|rrrrr|用因果与结果简查已有故事，不把检查句式当成必选模板。
linear-chronology|oiooo|需要确定按实际发生顺序讲述，已有叙述约定则直接继承。
reverse-opening-backfill|--ooo|具体设计开场时，先展示结果再补来路。
flashback-insertion|---oo|当前行动需要过去信息才能改变判断。
dual-timeline|oioo-|两条时间线都是主结构的一部分。
nonlinear-mosaic|oioo-|作品明确依靠非线性呈现构成核心阅读体验。
circular-chronology|oiooo|相似起点需要通过新选择产生不同意义。
in-medias-res|--ooo|已进入开场或场景设计，需要从正在发生的行动切入。
reverse-chronology|oioo-|倒推原因本身构成作品或本卷的主要阅读方式。
flashforward-prolepsis|---oo|具体场景需要短暂预示未来，且不提前耗尽核心答案。
parallel-simultaneous-time|--ooo|同一时段的不同地点行动确实相互影响。
time-ellipsis|--ooo|重复稳定过程不值得展开，只交代影响后续的变化。
goal-action-consequence|rrcco|具体推进人物行动时梳理目标与后果；宏观层只简查。
causal-chain|rrrrr|复核关键事件能否承接，按作者创意尺度处理，不硬审写实逻辑。
escalation-ladder|occco|成长或对抗需要升级责任、范围或难度，不只是换强敌。
consequence-reversal|--ooo|具体反转由此前选择的后果引发。
mckee-causality|--ooo|关键事件需要通过价值变化和危机选择推动人物。
try-fail-cycle|--cco|旧办法多次碰壁确实服务当前故事，不强迫无敌文先失败。
yes-but-no-and|--oco|当前行动需要带着变化继续，而非成功失败都归零。
consequence-propagation|ooooo|主角重大行为需要影响其他人物、组织或后续阶段。
forced-decision-fork|--ooo|已经设计具体关键选择，需要明确舍弃与开启的路径。
direct-opposition|oiooo|主角和主要对手争取互不相容的结果。
antagonist-counterplan|--ooo|开始设计本卷或事件的具体博弈，对手需要主动反制。
internal-external-bind|oiooo|长期成长依赖内在习惯与外部问题相互作用。
true-dilemma|--ooo|本次确有无法兼得的价值选择，作者没有要求回避这类代价。
ticking-clock|--ooo|当前具体任务有成立的期限，不能为了制造刺激凭空加期限。
resource-squeeze|--ooo|具体行动受资源限制，需要规划可用办法。
multi-front-pressure|--ooo|本卷或事件同时承担多个互相牵动的目标。
false-victory-defeat|--ooo|需要为本卷或事件设计表面结果与真实意义的差异。
scene-goal-conflict-turn-result|---oc|当前章节或场景要围绕具体目标形成变化。
scene-sequel-cycle|---cc|行动之后需要反应和决定，不强制交替篇数。
reaction-dilemma-decision|---oo|人物需要消化重大结果，再决定下一步。
scene-value-shift|---rr|检查场景状态变化；允许日常和感受积累，不要求每场反转。
enter-late-exit-early|----c|具体写场景时减少无作用的开场和收尾。
motivation-reaction-unit|----c|正文中需要理顺刺激、感受和行动的先后。
scene-question-turn|---cc|当前场景围绕一个即时问题推进。
action-reaction-balance|---oc|动作、旁人反应和人物感受需要配平。
positive-growth-arc|cio--|主角的长期方向确实包含成长，不等于必须不断升级境界。
steadfast-arc|cio--|主角信念或能力较稳定，故事重点是影响世界与接受检验。
corruption-arc|oio--|作者接受人物逐渐腐化的长期方向。
tragic-fall-arc|oio--|作者接受悲剧坠落，不能因模板需要擅自安排悲剧。
redemption-arc|oio--|主角有需要承担的旧错，救赎是核心故事方向。
circular-character-arc|oio--|长期变化要以回到相似处境后的不同选择体现。
disillusionment-arc|oio--|失去旧信念、面对真相是长期成长核心。
want-need-gap|oioo-|主角追求和真实缺口的差异能驱动长期经历。
lie-truth-transition|oioo-|改变核心错误信念是主角长期故事的一部分。
wound-defense-choice|--ooo|开始具体人设、关系和选择设计时才展开创伤机制。
trust-ladder|oiooo|信任变化属于核心关系线；普通配角关系留到下层。
attraction-obstacle-commitment|oiooo|亲密关系是核心故事动力，而非随手附加感情线。
rivalry-respect-arc|oiooo|竞争关系长期影响主角方向和选择。
alliance-under-pressure|oiooo|核心故事围绕利益不同者合作与裂痕展开。
betrayal-repair-arc|oiooo|背叛与修复属于核心关系方向，不能强制原谅。
mentor-inheritance-arc|oiooo|师承、继承或超越导师是长期主线。
family-repair-boundary|oiooo|家庭关系变化是核心故事，而非背景点缀。
shared-mystery|oiooo|查明一个核心未知本身就是追读动力。
withheld-secret|--ooo|具体安排持有秘密者的行为和信息释放。
dramatic-irony|--ooo|需要设计读者与人物知情程度的差异。
information-asymmetry|--oco|具体博弈依赖不同人物掌握不同事实。
progressive-reveal|ooooo|核心谜团已经选定，需要按阶段决定揭晓责任。
suspense-pressure|--ooo|具体设计当前未决问题带来的危险和期待。
central-dramatic-question|oiooo|全书方向需要明确一个可持续追踪的核心问题。
fair-play-clue-chain|--ooo|已进入案件或谜团的具体证据设计。
red-herring-control|--ooo|具体调查需要合理误判，而非临时改答案。
setup-payoff|oooco|需要分配承诺的铺设和回收，不在全书阶段预埋全部细节。
delayed-context-reframe|--ooo|具体信息设计需要用新语境改变既有事实的含义。
anticipation-pressure-release|--ooo|当前单元需要蓄积与释放期待，符合作者爽感或情绪目标。
tension-relief|-ccoo|粗分卷或单元节奏需要高压与消化空间的分配。
hope-despair-cycle|--ooo|作者接受希望和挫败交替，不强迫轻松题材受虐。
emotional-staircase|ooooo|人物情感投入需要随阶段逐步加深。
payoff-afterglow|--ooo|重要结果已经发生，需要让人物与世界回应。
emotional-contrast|--ooo|相邻事件或场景需要不同情绪互相衬托。
cathartic-release|--ooo|已经建立的长期情绪到达可兑现的关键节点。
dread-accumulation|--ooo|作者选择恐怖或不安体验，需要具体异常逐步累积。
comic-relief|--ooo|高压故事需要符合人物的短暂轻松。
scene-summary-balance|----c|写章节时决定哪些场景展开、哪些过程概述。
narrative-compression|----o|正文跨过较长过程时保留必要变化。
dramatic-expansion|----o|正文中的关键决定或情绪瞬间需要放慢。
acceleration-deceleration|-oooo|粗分卷调篇幅权重，细层调事件密度；不直接规定每章速度。
crosscutting-pressure|---oo|多处同时行动要靠切换共同推进结果。
montage-compression|----o|正文需要用短片段表现训练或建设过程。
strategic-pause|---oo|重大信息前后需要理解、观察或关系反应。
opening-promise|-oooo|只在首卷或开篇设计时落实核心卖点和第一次有效结果。
progression-loop|cicoo|长期动力来自能力、资源、地位或组织的持续积累。
pressure-payoff-loop|oiooo|长期阅读动力包含承压、准备与兑现，不只限于打脸。
promise-progress-payoff|cccoo|需要将核心承诺、阶段进展和兑现对应起来。
arc-close-next-open|-ccoo|当前阶段要收束，又要从结果交给下一阶段。
recovery-window|-oooo|阶段之间确实需要恢复、日常或关系推进。
chapter-micro-arc|----r|复核本章有没有可感知的推进，不强制独立闭环或大转折。
partial-answer-new-question|---oo|章节或事件已到回答旧问题、打开新问题的时机。
cliffhanger-spectrum|----c|设计章末去向，可留危险、发现、决定或余韵。
open-loop-budget|rrrrr|复核已开线索是否被追踪；不要求设计成员每次阅读库介绍。
recap-through-consequence|----o|正文需要提醒前情时，通过当前后果自然带出。
limited-viewpoint|--ooo|确定或继承具体叙述视角，不在方向选择时重复决策。
multi-viewpoint|--ooo|已经选定多线结构后，规划具体视角分工。
omniscient-viewpoint|--ooo|具体叙述明确采用全知视角，需要管理知情范围。
unreliable-narrator|oiooo|不可靠讲述构成全书核心卖点或具体悬念装置。
objective-camera-viewpoint|----o|正文明确选择只展示可观察行为。
first-person-voice|----o|已经确认用第一人称，执行人物独有声音。
second-person-address|----o|作者明确需要第二人称或特殊互动表达。
free-indirect-discourse|----o|第三人称正文需要自然融入人物判断。
documentary-narrative|oiooo|书信、档案等构成作品主要叙事形式或当前关键材料。
meta-narrative|oiooo|讲故事或作品规则本身就是核心创意。
symbolic-motif|--ooo|已经选定重要意象，需要在具体阶段赋予不同意义。
stream-of-consciousness|----o|作者风格明确需要按感知与联想呈现意识。
interior-monologue|----o|具体写人物未说出口的矛盾与选择。
counterpoint-juxtaposition|---oo|并置具体场景或语言形成反差，不等于全书双线结构。
defamiliarization|----o|具体表达需要从陌生角度呈现熟悉事物。
thematic-question|oiooo|作者要求立意方向时，用问题表达，不能强加说教主题。
value-opposition|oiooo|作品的核心冲突包含两种有吸引力的价值选择。
foil-character|--ooo|进入具体角色分工时，设置与主角形成反衬的人物。
counterargument-character|--ooo|已有主题需要由真实行动与对手立场检验。
moral-choice-proof|--ooo|具体选择需要体现已选价值，不强制每个题材承担道德论证。
motif-transformation|--ooo|与象征与重复意象同义，保留来源并归入同一主卡。
closed-ending|oiooo|需要在方向层确定核心承诺最终能否明确落定。
open-ending|oiooo|作者接受部分结果保持歧义或开放；不等于没有阶段回报。
mirror-structure|oiooo|开头和结尾的对应能体现人物或处境变化。
bittersweet-ending|oiooo|当前完整故事需要苦甜并存的收束；不强制永久损失。
twist-ending|oiooo|作者选择以可回看证据重释前文的收束方向。
denouement|--ooo|高潮之后需要结算当前人物与局势后果。
epilogue|--o-o|具体收尾需要稍后时间的长期余味。
closure-hierarchy|rrrrr|复核主承诺与阶段承诺的关闭责任，避免列为必套模板。
`.trim();
