-- R192/P0 additive storage. No old planning data is changed or copied.
CREATE TABLE tm2_books(owner TEXT NOT NULL,book TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 0,manifest TEXT NOT NULL,adoption TEXT,PRIMARY KEY(owner,book)) STRICT;
CREATE TABLE tm2_candidates(owner TEXT NOT NULL,book TEXT NOT NULL,id TEXT NOT NULL,revision INTEGER NOT NULL,body TEXT NOT NULL,hash TEXT NOT NULL,PRIMARY KEY(owner,book,id,revision),FOREIGN KEY(owner,book) REFERENCES tm2_books(owner,book)) STRICT;
CREATE TABLE tm2_reviews(owner TEXT NOT NULL,book TEXT NOT NULL,candidate TEXT NOT NULL,revision INTEGER NOT NULL,reviewer TEXT NOT NULL,verdict TEXT NOT NULL CHECK(verdict IN ('pass','revise')),PRIMARY KEY(owner,book,candidate,revision),FOREIGN KEY(owner,book,candidate,revision) REFERENCES tm2_candidates(owner,book,id,revision)) STRICT;
CREATE TABLE tm2_numbers(owner TEXT NOT NULL,book TEXT NOT NULL,kind TEXT NOT NULL,stable_id TEXT NOT NULL,number INTEGER NOT NULL CHECK(number>0),PRIMARY KEY(owner,book,kind,stable_id),UNIQUE(owner,book,kind,number),FOREIGN KEY(owner,book) REFERENCES tm2_books(owner,book)) STRICT;
CREATE TABLE tm2_adoptions(owner TEXT NOT NULL,book TEXT NOT NULL,id TEXT NOT NULL,candidate TEXT NOT NULL,candidate_revision INTEGER NOT NULL,revision INTEGER NOT NULL,mapping TEXT NOT NULL,PRIMARY KEY(owner,book,id),UNIQUE(owner,book,revision),FOREIGN KEY(owner,book,candidate,candidate_revision) REFERENCES tm2_candidates(owner,book,id,revision)) STRICT;
CREATE TABLE tm2_operations(owner TEXT NOT NULL,book TEXT NOT NULL,operation TEXT NOT NULL,key TEXT NOT NULL,request_hash TEXT NOT NULL,response TEXT NOT NULL,PRIMARY KEY(owner,book,operation,key),FOREIGN KEY(owner,book) REFERENCES tm2_books(owner,book)) STRICT;
CREATE TABLE tm2_outbox(sequence INTEGER PRIMARY KEY AUTOINCREMENT,owner TEXT NOT NULL,book TEXT NOT NULL,id TEXT NOT NULL UNIQUE,kind TEXT NOT NULL,body TEXT NOT NULL,FOREIGN KEY(owner,book) REFERENCES tm2_books(owner,book)) STRICT;
CREATE TABLE tm2_consumptions(owner TEXT NOT NULL,book TEXT NOT NULL,event TEXT NOT NULL,consumer TEXT NOT NULL,PRIMARY KEY(owner,book,event,consumer),FOREIGN KEY(event) REFERENCES tm2_outbox(id)) STRICT;
