import {describe,it,expect} from 'vitest';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {CreativeReferenceRuntime,creativeSupplement} from '../../apps/api/src/application/creative-reference/runtime.js';
import {SqliteCreativeReferenceRepository} from '../../apps/api/src/infrastructure/db/repositories/creative-reference-repository.js';
function fixture(){const db=new DatabaseSync(':memory:');for(const f of ['0122_creative_reference.sql','0124_creative_reference_sessions.sql'])db.exec(readFileSync('apps/api/src/infrastructure/db/migrations/'+f,'utf8'));const repo=new SqliteCreativeReferenceRepository(db);const c=repo.createCard({assetKind:'method',idempotencyKey:'one',legacy:null,authorActor:'writer',payload:{assetKind:'method',schemaVersion:1,name:'余韵',shortPhrase:'余韵',summary:'让结果留下影响',aliases:[],method:{title:'余韵',instruction:'用反应表现变化',boundary:'不重复解释',usageTree:'阶段回报',relatedPurposes:['情绪回报'],applicableLayers:['book'],conditionalUses:[{stage:'setting',condition:'涉及仪式',use:'通过规则表达纪念'}],aliases:[]}}},'2026-09-14');repo.reviewRevision({internalId:c.internalId,expectedRevision:1,reviewActor:'reviewer'},'2026-09-14');const release=repo.publishRelease({entries:[{internalId:c.internalId,revision:1}],relations:[],publishedBy:'publisher',expectedActiveReleaseId:null},'2026-09-14');return {db,repo,release,id:c.displayCode};}
const input={ownerId:'owner',bookId:'book',sessionId:'job',stage:'book' as const,source:'主角洗清冤屈，作者希望轻松且感到尊严恢复'};
describe('真实冻结创作库工具循环',()=>{
 it('长句拆词，空命中提示同用途候选，错误后仍能读候选',async()=>{const {db,id}=fixture();try{const actions=[{action:'search',purpose:'情绪回报',query:'陌生词 未收录',conditional:false,cursor:0},{action:'read',ids:['错误编号']},{action:'read',ids:[id]},{action:'ready',selected:[{id,application:'以交还钥匙表现改变'}]}];const r=await new CreativeReferenceRuntime(db).select(input,async(i,p)=>{if(i===1)expect(p).toContain('purpose_fallback');if(i===2)expect(p).toContain(id);return JSON.stringify(actions[i]);});expect(r.selected[0].id).toBe(id);}finally{db.close();}});
 it('关联用途搜索、读详情、选定并注入，恢复不重调模型',async()=>{const {db,id}=fixture();try{const runtime=new CreativeReferenceRuntime(db),prompts:string[]=[];const actions=[{action:'search',purpose:'情绪回报',query:'',conditional:false,cursor:0},{action:'read',ids:[id]},{action:'ready',selected:[{id,application:'用同伴交还钥匙表现信任恢复'}]}];const result=await runtime.select(input,async(i,p)=>{prompts.push(p);return JSON.stringify(actions[i]);});expect(prompts[1]).toContain(id);expect(prompts[2]).toContain('不重复解释');expect(creativeSupplement(result)).toContain('用同伴交还钥匙');expect(result.selected).toHaveLength(1);await runtime.select(input,async()=>{throw Error('不应重调');});}finally{db.close();}});
 it('未读引用被拒绝，最终可原创，不编造使用',async()=>{const {db,id}=fixture();try{const r=await new CreativeReferenceRuntime(db).select(input,async(i,p)=>{if(i===0)return JSON.stringify({action:'ready',selected:[{id,application:'假装读过'}]});expect(p).toContain('已读');return JSON.stringify({action:'ready',selected:[]});});expect(r.selected).toEqual([]);}finally{db.close();}});
 it('条件阶段需显式扩大，来源与owner/book冻结不混用',async()=>{const {db}=fixture();try{const runtime=new CreativeReferenceRuntime(db);const x={...input,stage:'setting' as const};await runtime.select(x,async(i,p)=>{if(i===0)return JSON.stringify({action:'search',purpose:'情绪回报',query:'',conditional:false,cursor:0});if(i===1){expect(p).toContain('"total":0');return JSON.stringify({action:'search',purpose:'情绪回报',query:'',conditional:true,cursor:0});}expect(p).toContain('"total":1');return JSON.stringify({action:'ready',selected:[]});});await expect(runtime.select({...x,source:'被修改'},async()=>'' )).rejects.toThrow('资料已变化');let called=false;await runtime.select({...x,ownerId:'other'},async()=>{called=true;return '{"action":"ready","selected":[]}';});expect(called).toBe(true);}finally{db.close();}});
 it('无正式版本不读取草稿；预算不截断书籍',async()=>{const {db,repo}=fixture();try{db.prepare('UPDATE creative_reference_releases SET active=0').run();let called=false;const r=await new CreativeReferenceRuntime(db).select(input,async()=>{called=true;return '';});expect(called).toBe(false);expect(r.releaseId).toBeNull();}finally{db.close();}const f=fixture();try{const r=await new CreativeReferenceRuntime(f.db).select({...input,source:'字'.repeat(11000)},async()=>{throw Error('不发送');});expect(r.selected).toEqual([]);expect(r.note).toContain('预算');}finally{f.db.close();}});
 it('查询未知结果恢复沿用冻结发布，不跟随新活动版本',async()=>{const {db,release}=fixture();try{const runtime=new CreativeReferenceRuntime(db);await expect(runtime.select(input,async()=>{throw Error('unknown');})).rejects.toThrow('unknown');db.prepare('UPDATE creative_reference_releases SET active=0').run();const r=await runtime.select(input,async()=>'{"action":"ready","selected":[]}');expect(r.releaseId).toBe(release.releaseId);}finally{db.close();}});
});
