import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {CreativeReferenceRuntime,creativeSupplement} from '../../apps/api/src/application/creative-reference/runtime.js';
import {SqliteCreativeReferenceRepository} from '../../apps/api/src/infrastructure/db/repositories/creative-reference-repository.js';
import {validatePayload} from '../../apps/api/src/application/creative-reference/validation.js';
const plan=JSON.parse(readFileSync('scripts/creative-library/generated/chain-variants.json','utf8'));
describe('独立节奏余韵卡仅供链分章',()=>{
 it('原33卡恢复，新增32卡保持来源结构并限制0—3章',()=>{const c5=JSON.parse(readFileSync('scripts/creative-library/generated/chain-rhythm.json','utf8'));expect(plan.entries).toHaveLength(33);expect(plan.additions).toHaveLength(32);for(const e of plan.entries)expect(e.payload).toEqual(c5.entries.find((s:any)=>s.identity===e.identity).expectedPayload);for(const a of plan.additions){validatePayload(a.payload);expect(a.payload.method.applicableLayers).toEqual(['chain_chapters']);expect(a.payload.method.conditionalUses).toEqual([]);expect(a.payload.method.boundary).toContain(a.sourceCode);expect(a.payload.method.instruction).toContain('余韵0—3章');expect(a.payload.method.instruction).toContain('最多3章，可以不写');}});
 it.each(['book','volume','chain','chapter','prose','chain_chapters'] as const)('%s检索及最终注入边界',async stage=>{const db=new DatabaseSync(':memory:');try{for(const f of ['0122_creative_reference.sql','0124_creative_reference_sessions.sql'])db.exec(readFileSync('apps/api/src/infrastructure/db/migrations/'+f,'utf8'));const repo=new SqliteCreativeReferenceRepository(db),p=plan.additions.find((x:any)=>x.sourceCode==='法013').payload,c=repo.createCard({assetKind:'method',idempotencyKey:'variant',legacy:null,authorActor:'test',payload:p},'now');repo.reviewRevision({internalId:c.internalId,expectedRevision:1,reviewActor:'other'},'now');repo.publishRelease({entries:[{internalId:c.internalId,revision:1}],relations:[],publishedBy:'test',expectedActiveReleaseId:null},'now');
 const r=await new CreativeReferenceRuntime(db).select({ownerId:'o',bookId:'b',sessionId:stage,stage,source:'按已经确定的本链故事安排章节'},async(i,prompt)=>{if(i===0)return JSON.stringify({action:'search',purpose:'宏观节奏',query:'',conditional:true,cursor:0});if(stage!=='chain_chapters'){expect(prompt).toContain('"total":0');return '{"action":"ready","selected":[]}';}if(i===1)return JSON.stringify({action:'read',ids:[c.displayCode]});return JSON.stringify({action:'ready',selected:[{id:c.displayCode,application:'按三幕安排本链章节，结果已收束则不加余韵章'}]});});expect(r.selected.length).toBe(stage==='chain_chapters'?1:0);const output=creativeSupplement(r);expect(output.includes('兑现与余韵检查（链页面·链分章）')).toBe(stage==='chain_chapters');if(stage==='chain_chapters'){expect(output).toContain('最多3章');expect(output).toContain('可以不写');}}finally{db.close();}});
});
